apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rtgcgkid
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-rtgcgkid:b09f83bc5ee2c2f7390e538110d076dfa0167464@sha256:752ece7c7746f2d41ebf610cc739702f078b4b741b153de72e22ed57f1607981
          name: container-image
